version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    IMAGE_REPO_NAME: lab2-frontend   # repo ECR
    CONTAINER_NAME: app              # nombre EXACTO del contenedor en la TaskDefinition

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} \
          | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - COMMIT_HASH="${CODEBUILD_RESOLVED_SOURCE_VERSION:-manual}"
      - IMAGE_TAG=$(echo "${COMMIT_HASH}" | cut -c1-7); [ -n "${IMAGE_TAG}" ] || IMAGE_TAG="manual-$(date +%Y%m%d%H%M%S)"
  build:
    commands:
      - echo "Build -> ${REPOSITORY_URI}:${IMAGE_TAG}"
      - docker build --no-cache -t ${REPOSITORY_URI}:latest .
      - docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - docker push ${REPOSITORY_URI}:latest
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - printf '[{"name":"%s","imageUri":"%s"}]' "${CONTAINER_NAME}" "${REPOSITORY_URI}:${IMAGE_TAG}" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
